"""
System-1: Screen Analyzer Subagent
Visual analysis of the current Windows host screenshot.
Uses a multimodal model (VLM) capable of interpreting images.
"""
import os
from pydantic import BaseModel, Field
from typing import Optional
from ..prompts.system1_screen import SYSTEM1_SCREEN_PROMPT
from ..tools.screen_tools import get_latest_screenshot, describe_screen_region


class UIElement(BaseModel):
    """A detected interactive element on the screen."""
    element: str = Field(description="Name or label of the element")
    type: str = Field(description="button | input | menu | link | icon | text")
    approximate_x: int = Field(description="Approximate X coordinate in pixels")
    approximate_y: int = Field(description="Approximate Y coordinate in pixels")


class ScreenAnalysis(BaseModel):
    """Structured output from the screen analyzer subagent."""
    current_application: str = Field(description="Name of the application currently in focus")
    screen_description: str = Field(description="Paragraph describing what is visible on screen")
    interactive_elements: list[UIElement] = Field(description="List of visible interactive elements")
    is_loading: bool = Field(description="Whether the screen appears to be loading")
    has_error_dialog: bool = Field(description="Whether an error dialog is visible")
    error_dialog_text: Optional[str] = Field(default=None, description="Text of any error dialog")
    recommended_next_ui_action: str = Field(description="What the agent should do next on this screen")


# SubAgent dictionary — registered with create_deep_agent() in orchestrator.py
screen_analyzer_subagent = {
    "name": "screen-analyzer",
    "description": (
        "Analyzes the current screenshot of the operator's Windows screen. "
        "Use this to understand what application is open, what UI elements are visible, "
        "and what the next screen interaction should be. "
        "Returns a structured analysis with element coordinates."
    ),
    "system_prompt": SYSTEM1_SCREEN_PROMPT,
    "tools": [get_latest_screenshot, describe_screen_region],
    # Use local Qwen model. Note: For vision tasks, we rely on the Set-of-Marks image
    # generated by OmniParser and processed by the multimodal capabilities of Qwen VL.
    # In a fully edge setup, this would point to Qwen-VL or similar.
    "model": os.getenv("ORCHESTRATOR_MODEL", "Qwen/Qwen3.5-27B-FP8"),
    "response_format": ScreenAnalysis,
}
